<?php
echo "Php version : "           . PHP_VERSION         . "<br/>";
echo "Php major version : "     . PHP_MAJOR_VERSION         . "<br/>";
echo "Php minor version : "     . PHP_MINOR_VERSION         . "<br/>";
echo "Php release version : "   . PHP_RELEASE_VERSION         . "<br/>";
echo "Php version ID : "        . PHP_VERSION_ID         . "<br/>";
echo "Php extra version : "     . PHP_EXTRA_VERSION         . "<br/>";
echo "Php zts : "               . PHP_ZTS         . "<br/>";
echo "Php debug : "             . PHP_DEBUG         . "<br/>";
echo "Php max path length : "   . PHP_MAXPATHLEN         . "<br/>";
echo "Php os : "                . PHP_OS         . "<br/>";
echo "Php os family : "         . PHP_OS_FAMILY         . "<br/>";
echo "Php sapi : "              . PHP_SAPI         . "<br/>";
echo "Php end of line : "       . PHP_EOL         . "<br/>";
echo "Php int max : "           . PHP_INT_MAX         . "<br/>";
echo "Php int min : "           . PHP_INT_MIN         . "<br/>";
echo "Php int size : "          . PHP_INT_SIZE         . "<br/>";
echo "Php float dig : "         . PHP_FLOAT_DIG         . "<br/>";
echo "Php float epsilon : "     . PHP_FLOAT_EPSILON         . "<br/>";
echo "Php float max : "         . PHP_FLOAT_MAX         . "<br/>";
echo "Php float min : "         . PHP_FLOAT_MIN         . "<br/>";
echo "Php default include path : " . DEFAULT_INCLUDE_PATH         . "<br/>";
echo "Php pear install dir : "  . PEAR_INSTALL_DIR        . "<br/>";
echo "Php pear extension dir : " . PEAR_EXTENSION_DIR        . "<br/>";
echo "Php extension dir : "     . PHP_EXTENSION_DIR        . "<br/>";
echo "Php prefix : "            . PHP_PREFIX        . "<br/>";
echo "Php binder : "            . PHP_BINDIR        . "<br/>";
echo "Php binary : "            . PHP_BINARY        . "<br/>";
echo "Php binary read : "       . PHP_BINARY_READ        . "<br/>";
echo "Php man dir : "           . PHP_MANDIR       . "<br/>";
echo "Php lib dir : "           . PHP_LIBDIR       . "<br/>";
echo "Php data dir : "          . PHP_DATADIR       . "<br/>";
echo "Php sysconf dir : "       . PHP_SYSCONFDIR       . "<br/>";
echo "Php local state dir : "   . PHP_LOCALSTATEDIR       . "<br/>";
echo "Php config file at : "    . PHP_CONFIG_FILE_PATH       . "<br/>";
echo "Php config file scan dir : " . PHP_CONFIG_FILE_SCAN_DIR       . "<br/>";
echo "Php shlib suffix : "      . PHP_SHLIB_SUFFIX       . "<br/>";
echo "Php fd setsize : "        . PHP_FD_SETSIZE       . "<br/>";
echo "Php e_error : "           . E_ERROR       . "<br/>";
echo "Php e_warning : "         . E_WARNING       . "<br/>";
echo "Php e_parse : "           . E_PARSE       . "<br/>";
echo "Php e_notice : "          . E_NOTICE       . "<br/>";
echo "Php e_core_error : "      . E_CORE_ERROR       . "<br/>";
echo "Php e_core_warning : "    . E_CORE_WARNING       . "<br/>";
echo "Php e_compile_error : "   . E_COMPILE_ERROR       . "<br/>";
echo "Php e_compile_warning : " . E_COMPILE_WARNING       . "<br/>";
echo "Php e_user_error : "      . E_USER_ERROR       . "<br/>";
echo "Php e_user_warning : "    . E_USER_WARNING       . "<br/>";
echo "Php e_user_notice : "     . E_USER_NOTICE       . "<br/>";
echo "Php e_deprecated : "      . E_DEPRECATED       . "<br/>";
echo "Php e_user_deprecated : " . E_USER_DEPRECATED       . "<br/>";
echo "Php e_all : "             . E_ALL       . "<br/>";
echo "Php e_strict : "          . E_STRICT       . "<br/>";
